name = "Osprey"
license = "Apache License 2.0"
licenselink = "https://github.com/tomanistor/osprey/blob/master/LICENSE.md"
description = "Clean, responsive one-page portfolio accompanied by a minimalist blog."
homepage = "https://github.com/tomanistor/osprey"
tags = ["blog", "portfolio", "gallery", "minimalist", "responsive", "flexbox"]
features = ["blog", "portfolio", "google analytics"]
min_version = "0.5"

[author]
  name = "Toma Nistor"
  homepage = "https://tomanistor.com"
